name: Build and deploy Storybook to Azure Web App

on:
  push:
    branches:
      - latest
      - master
  pull_request:
    branches:
      - latest
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: yarn install
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: build library
        run: yarn build

      - name: lerna version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
        run: |
          git push --set-upstream origin HEAD
          yarn release -- --yes

      - name: lerna publish
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_ACCESS_TOKEN}"
          yarn publish -- --no-verify-access --yes
          npm config delete "//registry.npmjs.org/:_authToken"
